### PR TITLE
Add dedicated export paths for Node.js and web versions in package.json

### LINKED ISSUE #7: v2.0.0 module doesn't correctly load in Node.js when using a dynamic import
Based on the changelog, I understand that `v2.0.0` transitions to using ESM modules.

There seems to be a few problems preventing it from loading correctly (`v1.0.0` has been working correctly for me for a long time). I'm using Node `v22.3.0`.

I'm getting the error:

```
SyntaxError: Unexpected token 'export'
```

I think this may be caused by the `package.json` file for `v2.0.0` lacking:

```
"type": "module"
```

Without this (as far as I know), Node doesn't parse the module as an ESM module, so it can't recognize `export`.

If I add that, the module does load, but then when calling `cut`, I'm getting the error:

```
Cannot read properties of undefined (reading '__wbindgen_add_to_stack_pointer')
```

I'm not sure exactly what is causing this error. Maybe the reference to the wrapper module (the module that contains the methods imported from WASM) isn't initialized correctly.

### PR DESCRIPTION
**Pull request by rotemdan**
Added dedicated paths to allow explicitly importing the Node.js version via `jieba-wasm/node` and the web version via `jieba-wasm/web`. Also reorder the conditional to resolve better for dynamic imports.

**Edit**: I can rename the path `/node` to `/nodejs` if you prefer.

Resolves #7

### CODE REVIEW

**Comment by fengkx** [comment]
Subpath is no longer need

**Comment by rotemdan** [comment]
The subpath may not be fully necessary for common usage, but there may be cases where it could help to specify exactly which version is reference, maybe for example to import types using TypeScript, like:

```ts
import { type ... } from 'jieba-wasm/node'
```
or maybe:
```ts
const jiebaNode: import('jieba-wasm/node')
const jiebaWeb: import('jieba-wasm/web')
```

I haven't tested in practice how TypeScript would resolve the type references, but I think in general it would be helpful to be able to reference the version explicitly, possibly for other special cases.

**Comment by fengkx** [comment]
Make sense to me

**Comment by fengkx** [comment]
Merged, Thanks

**Pull request merged**
